services:
  #Service Offre
  service-offres:
    image: service-offres:1.0.0
    container_name: service-offres
    depends_on:
      - service-postgres
#    ports:
#        - 8082:8082
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    network_mode: "host"

  #Service Personne
  service-personnes:
    image: service-personnes:1.0.0
    container_name: service-personnes
    depends_on:
      - service-postgres
#    ports:
#      - 8083:8083
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    network_mode: "host"

  #Service Postgresql
  service-postgres:
    container_name: container-service-postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - service-postgres:/data/postgres
    network_mode: "host"
#    ports:
#      - "5432:5432"
    restart: unless-stopped

volumes:
  service-postgres:
