services:
  #Service Offre
  service-offres:
    image: service-offres:0.0.1-SNAPSHOT
    container_name: service-offres
    depends_on:
      - service-postgres
    ports:
        - 8082:8082
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.19.2.jar
      - OTEL_SERVICE_NAME=service-offres

  #Service Personne
  service-personnes:
    image: service-personnes:0.0.1-SNAPSHOT
    container_name: service-personnes
    depends_on:
      - service-postgres
    ports:
      - 8083:8083
    environment:
      - JAVA_TOOL_OPTIONS=-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.19.2.jar
      - OTEL_SERVICE_NAME=service-personnes

  #Service Postgresql
  service-postgres:
    container_name: container-service-postgres
    image: postgres:15.1
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - service-postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - service-postgres
    restart: unless-stopped

networks:
  service-postgres:
    driver: bridge

volumes:
  service-postgres:
