FROM eclipse-temurin:17.0.5_8-jre AS builder
WORKDIR workspace
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} intervenant-personnes.jar
RUN java -Djarmode=layertools -jar intervenant-personnes.jar extract
COPY agent/opentelemetry-javaagent-1.19.2.jar dependencies/BOOT-INF/lib/opentelemetry-javaagent-1.19.2.jar

FROM gcr.io/distroless/java17-debian11
USER nonroot
WORKDIR workspace
COPY --from=builder workspace/dependencies/ ./
COPY --from=builder workspace/spring-boot-loader/ ./
COPY --from=builder workspace/snapshot-dependencies/ ./
COPY --from=builder workspace/application/ ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]

