#FROM eclipse-temurin:17.0.5_8-jre AS builder
#WORKDIR workspace
#ARG JAR_FILE=target/*.jar
#COPY ${JAR_FILE} intervenant-offres.jar
#RUN java -Djarmode=layertools -jar intervenant-personnes.jar extract
#COPY agent/opentelemetry-javaagent-1.19.2.jar dependencies/BOOT-INF/lib/opentelemetry-javaagent-1.19.2.jar

#FROM gcr.io/distroless/java17-debian11
#USER nonroot
#WORKDIR workspace
#COPY --from=builder workspace/dependencies/ ./
#COPY --from=builder workspace/spring-boot-loader/ ./
#COPY --from=builder workspace/snapshot-dependencies/ ./
#COPY --from=builder workspace/application/ ./
#ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]

FROM eclipse-temurin:17.0.5_8-jre AS builder
EXPOSE 8082:8082
WORKDIR workspace
COPY target/service-offres-0.0.1-SNAPSHOT.jar service-offres.jar
ENTRYPOINT ["java","-jar","service-offres.jar"]